# Provision a Synapse External Bucket (http://docs.synapse.org/articles/custom_storage_location.html)
template_path: templates/SynapseExternalBucket.yaml
stack_name: GatesKI-TestStudy
parameters:
  # true for read-write bucket, false (default) for read-only bucket 
  AllowWriteBucket: 'true'
  # Synapse username
  SynapseUserName: 'jsmith'
  # true to encrypt bucket, false (default) for no encryption
  EncryptBucket: 'true'
  # 'Enabled' to enable bucket versioning, default is 'Suspended'
  BucketVersioning: 'Enabled'
  # Bucket owner's email address
  OwnerEmail: 'joe.smith@sagebase.org'
  # 'Enabled' to enable Glacier life cycle rule, default is 'Disabled'
  EnableGlacierLifeCycle: 'Enabled'
  # Number of days until S3 objects are moved to Glacier, default is 30
  GlacierTransition: '90'
  # Number of days (from creation) when objects are deleted from S3 and Glacier, default is 365000
  GlacierExpiration: '1825'
hooks:
  after_create:
    - !synapse_external_bucket

