# Provision an EC2 instance
template_path: templates/managed-ec2-ubuntu.yaml
stack_name: test-infra-2
parameters:
  # The Sage deparment for this resource
  Department: "CompOnc"
  # The Sage project this resource will be used for
  Project: "GENIE Infrastructure"
  # The resource owner
  OwnerEmail: "khai.do@sagebionetworks.org"
  # EC2 instance type (available types https://aws.amazon.com/ec2/instance-types/)
  InstanceType: "t2.nano"
  AMIId: "ami-02cc14ddb168c7e68"

  # Integration with our jumpcloud directory service (do not change)
  JcConnectKey: !ssm /infra/JcConnectKey
  JcServiceApiKey: !ssm /infra/JcServiceApiKey
  JcSystemsGroupId: !ssm /infra/JcSystemsGroupId
hooks:
  after_create:
    - !notify_ec2
